using Npgsql;
using System;
using System.Collections.Generic;
using System.Text;

namespace Students
{
    public static class DbHelper
    {
        private static string connString = "Host=localhost;Username=postgres;Password=postgres;Database=students05-40x";

        public static async Task CreateDbStructureAsync()
        {
            var query = "CREATE TABLE student (" +
                "id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, " +
                "lastname varchar(50) NOT NULL, " +
                "firstname varchar(50) NOT NULL, " +
                "\"group\" varchar(7) NOT NULL, " +
                "birthday datetime NOT NULL, " +
                "level varchar(20) NOT NULL DEFAULT 'Бакалавр', " +
                "speciality varchar(100) NOT NULL DEFAULT 'Математика', " +
                "PRIMARY KEY (id)" +
                ")";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            await cmd.ExecuteNonQueryAsync();
        }
    }
}
