using Npgsql;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;

namespace Students
{
    public static class DbHelper
    {
        private static string connString = "Host=localhost;Username=postgres;Password=postgres;Database=students05-40x";

        public static async Task CreateDbStructureAsync()
        {
            var query = "CREATE TABLE IF NOT EXISTS student (" +
                "id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, " +
                "lastname varchar(50) NOT NULL, " +
                "firstname varchar(50) NOT NULL, " +
                "\"group\" varchar(7) NOT NULL, " +
                "birthday date NOT NULL, " +
                "level varchar(20) NOT NULL DEFAULT 'Бакалавр', " +
                "speciality varchar(100) NOT NULL DEFAULT 'Математика', " +
                "PRIMARY KEY (id)" +
                ")";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            await cmd.ExecuteNonQueryAsync();
        }

        public static async Task<long> SaveStudentAsync(Student student)
        {
            var query = "INSERT INTO student " +
                "(lastname, firstname, \"group\", birthday, level, speciality) " +
                "VALUES (" +
                "@lastname, @firstname, @group, @birthday, @level, @speciality" +
                //$"'{student.LastName}', '{student.FirstName}', '{student.Group}', '{student.Birthday.Year}-{student.Birthday.Month}-{student.Birthday.Day}', '{student.Level}', '{student.Speciality}' " + 
                ") RETURNING Id;";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            cmd.Parameters.AddWithValue("@lastname", student.LastName);
            cmd.Parameters.AddWithValue("@firstname", student.FirstName);
            cmd.Parameters.AddWithValue("@group", student.Group);
            cmd.Parameters.AddWithValue("@birthday", student.Birthday);
            cmd.Parameters.AddWithValue("@level", student.Level);
            cmd.Parameters.AddWithValue("@speciality", student.Speciality);
            long? result = (long?) await cmd.ExecuteScalarAsync();
            return result ?? -1L;
        }

        public static async Task<List<Student>> LoadStudentsAsync()
        {
            var query = "SELECT * FROM student";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            await using var reader = await cmd.ExecuteReaderAsync();
            var students = new List<Student>();
            while (await reader.ReadAsync())
            {
                var student = new Student()
                {
                    Id = reader.GetInt64(0),
                    LastName = reader.GetString(1),
                    FirstName = reader.GetString(2),
                    Group = reader.GetString(3),
                    Birthday = reader.GetDateTime(4),
                    Level = reader.GetString(5),
                    Speciality = reader.GetString(6)
                };
                students.Add(student);
            }
            return students;
        }

        public static async Task DeleteStudentInfoAsync(Student student)
        {
            var query = "DELETE FROM student WHERE id=@id";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            cmd.Parameters.AddWithValue("@id", student.Id);
            await cmd.ExecuteNonQueryAsync();
        }
    }
}
