using Npgsql;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;

namespace Students
{
    public static class DbHelper
    {
        private static string connString = "Host=localhost;Username=postgres;Password=postgres;Database=students05-40x";

        public static async Task CreateDbStructureAsync()
        {
            var query1 = "CREATE TABLE IF NOT EXISTS student (" +
                "id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, " +
                "lastname varchar(50) NOT NULL, " +
                "firstname varchar(50) NOT NULL, " +
                "\"group\" varchar(7) NOT NULL, " +
                "birthday date NOT NULL, " +
                "level varchar(20) NOT NULL DEFAULT 'Бакалавр', " +
                "speciality varchar(100) NOT NULL DEFAULT 'Математика', " +
                "PRIMARY KEY (id)" +
                ")";
            var query2 = "CREATE TABLE IF NOT EXISTS performance" +
                "(" +
                "id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, " +
                "student_id bigint NOT NULL," +
                "subject character varying(100) NOT NULL," +
                "points integer NOT NULL," +
                "CONSTRAINT performance_pkey PRIMARY KEY (id)," +
                "CONSTRAINT stud_subj UNIQUE (student_id, subject)," +
                "CONSTRAINT stud FOREIGN KEY (student_id) " +
                "REFERENCES public.student (id) MATCH SIMPLE " +
                "ON UPDATE CASCADE " +
                "ON DELETE RESTRICT, " +
                "CONSTRAINT points CHECK (points >= 0 AND points <= 100)" +
                ")";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd1 = new NpgsqlCommand(query1, conn);
            await cmd1.ExecuteNonQueryAsync();
            await using var cmd2 = new NpgsqlCommand(query2, conn);
            await cmd2.ExecuteNonQueryAsync();
        }

        public static async Task<long> SaveStudentAsync(Student student)
        {
            var query = "INSERT INTO student " +
                "(lastname, firstname, \"group\", birthday, level, speciality) " +
                "VALUES (" +
                "@lastname, @firstname, @group, @birthday, @level, @speciality" +
                //$"'{student.LastName}', '{student.FirstName}', '{student.Group}', '{student.Birthday.Year}-{student.Birthday.Month}-{student.Birthday.Day}', '{student.Level}', '{student.Speciality}' " + 
                ") RETURNING Id;";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            cmd.Parameters.AddWithValue("@lastname", student.LastName);
            cmd.Parameters.AddWithValue("@firstname", student.FirstName);
            cmd.Parameters.AddWithValue("@group", student.Group);
            cmd.Parameters.AddWithValue("@birthday", student.Birthday);
            cmd.Parameters.AddWithValue("@level", student.Level);
            cmd.Parameters.AddWithValue("@speciality", student.Speciality);
            long? result = (long?) await cmd.ExecuteScalarAsync();
            return result ?? -1L;
        }

        public static async Task<List<Student>> LoadStudentsAsync()
        {
            var query = "SELECT * FROM student";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            await using var reader = await cmd.ExecuteReaderAsync();
            var students = new List<Student>();
            while (await reader.ReadAsync())
            {
                var student = new Student()
                {
                    Id = reader.GetInt64(0),
                    LastName = reader.GetString(1),
                    FirstName = reader.GetString(2),
                    Group = reader.GetString(3),
                    Birthday = reader.GetDateTime(4),
                    Level = reader.GetString(5),
                    Speciality = reader.GetString(6)
                };
                students.Add(student);
            }
            return students;
        }

        public static async Task DeleteStudentInfoAsync(Student student)
        {
            var query = "DELETE FROM student WHERE id=@id";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            cmd.Parameters.AddWithValue("@id", student.Id);
            await cmd.ExecuteNonQueryAsync();
        }

        public static async Task SavePerformanceAsync(Performance performance)
        {
            var query = @"
                INSERT INTO performance (student_id, subject, popints)
                VALUES (@studentId, @subject, @points)
                ON CONFLICT (student_id, subject)
                DO UPDATE SET points = @points";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            cmd.Parameters.AddWithValue("@studentId", performance.StudentId);
            cmd.Parameters.AddWithValue("@subject", performance.Subject);
            cmd.Parameters.AddWithValue("@points", performance.Points);

            await cmd.ExecuteNonQueryAsync();
        }

        public static async Task DeletePerformanceAsync(long performanceId)
        {
            var query = "DELETE FROM performance WHERE id = @id";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            cmd.Parameters.AddWithValue("@id", performanceId);
            await cmd.ExecuteNonQueryAsync();
        }

        public static async Task<List<StudentsPerformance>> LoadPerformanceForStudentAsync(long studentId)
        {
            var query = @"
                SELECT
                    p.id as performance_id,
                    p.student_id,
                    s.lastname,
                    s.firsname,
                    p.subject,
                    p.points
                FROM performance p
                INNER JOIN student s
                ON p.student_id = s.id
                WHERE p.student_id = @studentId
                ORDER BY p.points
            ";
            await using var conn = new NpgsqlConnection(connString);
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            cmd.Parameters.AddWithValue("@studentId", studentId);

            await using var reader = await cmd.ExecuteReaderAsync();
            var results = new List<StudentsPerformance>();

            while(await reader.ReadAsync())
            {
                results.Add(new StudentsPerformance
                {
                    PerformanceId = reader.GetInt64(0),
                    StudentId = reader.GetInt64(1),
                    LastName = reader.GetString(2),
                    FirstName = reader.GetString(3),
                    Subject = reader.GetString(4),
                    Points = reader.GetInt32(5)
                });
            }

            return results;
        }
        
    }
}
